# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# Source :~ https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build and deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    - run: npm run lint
    - run: ls -alh dist

    - name: Deploy 🚀
      if: "github.event_name == 'release'"
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist     # The folder the action should deploy.

# End.
