# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
# Source :~ https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: Node.js CI

env:
  BOT_ID: survey
  # BOT_ID: demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build and deploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build:demo
    - run: npm run clean
      if: "BOT_ID == 'survey'"
    - run: npm run build:survey
      if: "BOT_ID == 'survey'"
    # - run: npm test
    - run: npm run lint --if-present
    - run: ls -lh dist
    - run: jq '.name' dist/corpus-en.json
    - run: jq '.data[].intent' dist/corpus-en.json

    - name: Deploy 🚀
      if: "github.event_name == 'release'"
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist     # The folder the action should deploy.
        commitMessage: "Deploying to 'gh-pages' from $GITHUB_REPOSITORY@$GITHUB_SHA ('$GITHUB_REF') 🚀"

    - name: No deploy 🚫
      if: "github.event_name != 'release'"
      run: echo No deploy on push

    - name: Test Deploy message
      # Deploying to gh-pages from @ 353aedd 🚀
      run: echo "Deploying to 'gh-pages' from $GITHUB_REPOSITORY@$GITHUB_SHA ('$GITHUB_REF') 🚀"

# End.
